export interface WC2026Player {
  name: string
  country: string
  position: 'goalkeeper' | 'defender' | 'midfielder' | 'forward'
}

export const WC2026_PLAYERS: WC2026Player[] = [
  // Algeria
  { name: "Oussama Benbot", country: "Algeria", position: "goalkeeper" },
  { name: "Melvin Mastil", country: "Algeria", position: "goalkeeper" },
  { name: "Luca Zidane", country: "Algeria", position: "goalkeeper" },
  { name: "Achref Abada", country: "Algeria", position: "defender" },
  { name: "Rayan Ait-Nouri", country: "Algeria", position: "defender" },
  { name: "Zinedine Belaid", country: "Algeria", position: "defender" },
  { name: "Rafik Belghali", country: "Algeria", position: "defender" },
  { name: "Ramy Bensebaini", country: "Algeria", position: "defender" },
  { name: "Samir Chergui", country: "Algeria", position: "defender" },
  { name: "Jaouen Hadjam", country: "Algeria", position: "defender" },
  { name: "Aissa Mandi", country: "Algeria", position: "defender" },
  { name: "Mohamed Amine Tougai", country: "Algeria", position: "defender" },
  { name: "Houssem Aouar", country: "Algeria", position: "midfielder" },
  { name: "Nabil Bentaleb", country: "Algeria", position: "midfielder" },
  { name: "Hicham Boudaoui", country: "Algeria", position: "midfielder" },
  { name: "Fares Chaibi", country: "Algeria", position: "midfielder" },
  { name: "Ibrahim Maza", country: "Algeria", position: "midfielder" },
  { name: "Yacine Titraoui", country: "Algeria", position: "midfielder" },
  { name: "Ramiz Zerrouki", country: "Algeria", position: "midfielder" },
  { name: "Mohamed Amine Amoura", country: "Algeria", position: "forward" },
  { name: "Nadhir Benbouali", country: "Algeria", position: "forward" },
  { name: "Adil Boulbina", country: "Algeria", position: "forward" },
  { name: "Fares Ghedjemis", country: "Algeria", position: "forward" },
  { name: "Amine Gouiri", country: "Algeria", position: "forward" },
  { name: "Anis Hadj Moussa", country: "Algeria", position: "forward" },
  { name: "Riyad Mahrez", country: "Algeria", position: "forward" },
  // Argentina
  { name: "Emiliano Martinez", country: "Argentina", position: "goalkeeper" },
  { name: "Geronimo Rulli", country: "Argentina", position: "goalkeeper" },
  { name: "Juan Musso", country: "Argentina", position: "goalkeeper" },
  { name: "Leonardo Balerdi", country: "Argentina", position: "defender" },
  { name: "Gonzalo Montiel", country: "Argentina", position: "defender" },
  { name: "Nicolas Tagliafico", country: "Argentina", position: "defender" },
  { name: "Lisandro Martinez", country: "Argentina", position: "defender" },
  { name: "Cristian Romero", country: "Argentina", position: "defender" },
  { name: "Nicolas Otamendi", country: "Argentina", position: "defender" },
  { name: "Facundo Medina", country: "Argentina", position: "defender" },
  { name: "Nahuel Molina", country: "Argentina", position: "defender" },
  { name: "Leandro Paredes", country: "Argentina", position: "midfielder" },
  { name: "Rodrigo De Paul", country: "Argentina", position: "midfielder" },
  { name: "Valentin Barco", country: "Argentina", position: "midfielder" },
  { name: "Giovani Lo Celso", country: "Argentina", position: "midfielder" },
  { name: "Exequiel Palacios", country: "Argentina", position: "midfielder" },
  { name: "Alexis Mac Allister", country: "Argentina", position: "midfielder" },
  { name: "Enzo Fernandez", country: "Argentina", position: "midfielder" },
  { name: "Julian Alvarez", country: "Argentina", position: "forward" },
  { name: "Lionel Messi", country: "Argentina", position: "forward" },
  { name: "Nicolas Gonzalez", country: "Argentina", position: "forward" },
  { name: "Thiago Almada", country: "Argentina", position: "forward" },
  { name: "Giuliano Simeone", country: "Argentina", position: "forward" },
  { name: "Nicolas Paz", country: "Argentina", position: "forward" },
  { name: "Jose Manuel Lopez", country: "Argentina", position: "forward" },
  { name: "Lautaro Martinez", country: "Argentina", position: "forward" },
  // Australia
  { name: "Mathew Ryan", country: "Australia", position: "goalkeeper" },
  { name: "Paul Izzo", country: "Australia", position: "goalkeeper" },
  { name: "Patrick Beach", country: "Australia", position: "goalkeeper" },
  { name: "Jordan Bos", country: "Australia", position: "defender" },
  { name: "Aziz Behich", country: "Australia", position: "defender" },
  { name: "Harry Souttar", country: "Australia", position: "defender" },
  { name: "Alessandro Circati", country: "Australia", position: "defender" },
  { name: "Lucas Herrington", country: "Australia", position: "defender" },
  { name: "Cameron Burgess", country: "Australia", position: "defender" },
  { name: "Kai Trewin", country: "Australia", position: "defender" },
  { name: "Milos Degenek", country: "Australia", position: "defender" },
  { name: "Jason Geria", country: "Australia", position: "defender" },
  { name: "Jacob Italiano", country: "Australia", position: "defender" },
  { name: "Jackson Irvine", country: "Australia", position: "midfielder" },
  { name: "Aiden O'Neill", country: "Australia", position: "midfielder" },
  { name: "Paul Okon Jr", country: "Australia", position: "midfielder" },
  { name: "Cameron Devlin", country: "Australia", position: "midfielder" },
  { name: "Connor Metcalfe", country: "Australia", position: "forward" },
  { name: "Mathew Leckie", country: "Australia", position: "forward" },
  { name: "Nishan Velupillay", country: "Australia", position: "forward" },
  { name: "Cristian Volpato", country: "Australia", position: "forward" },
  { name: "Nestory Irankunda", country: "Australia", position: "forward" },
  { name: "Awer Mabil", country: "Australia", position: "forward" },
  { name: "Ajdin Hrustic", country: "Australia", position: "forward" },
  { name: "Mohamed Toure", country: "Australia", position: "forward" },
  { name: "Tete Yengi", country: "Australia", position: "forward" },
  // Austria
  { name: "Patrick Pentz", country: "Austria", position: "goalkeeper" },
  { name: "Alexander Schlager", country: "Austria", position: "goalkeeper" },
  { name: "Florian Wiegele", country: "Austria", position: "goalkeeper" },
  { name: "David Affengruber", country: "Austria", position: "defender" },
  { name: "David Alaba", country: "Austria", position: "defender" },
  { name: "Kevin Danso", country: "Austria", position: "defender" },
  { name: "Marco Friedl", country: "Austria", position: "defender" },
  { name: "Philipp Lienhart", country: "Austria", position: "defender" },
  { name: "Phillipp Mwene", country: "Austria", position: "defender" },
  { name: "Stefan Posch", country: "Austria", position: "defender" },
  { name: "Alexander Prass", country: "Austria", position: "defender" },
  { name: "Michael Svoboda", country: "Austria", position: "defender" },
  { name: "Christoph Baumgartner", country: "Austria", position: "midfielder" },
  { name: "Carney Chukwuemeka", country: "Austria", position: "midfielder" },
  { name: "Florian Grillitsch", country: "Austria", position: "midfielder" },
  { name: "Konrad Laimer", country: "Austria", position: "midfielder" },
  { name: "Marcel Sabitzer", country: "Austria", position: "midfielder" },
  { name: "Xaver Schlager", country: "Austria", position: "midfielder" },
  { name: "Romano Schmid", country: "Austria", position: "midfielder" },
  { name: "Alessandro Schopf", country: "Austria", position: "midfielder" },
  { name: "Nicolas Seiwald", country: "Austria", position: "midfielder" },
  { name: "Paul Wanner", country: "Austria", position: "midfielder" },
  { name: "Patrick Wimmer", country: "Austria", position: "midfielder" },
  { name: "Marko Arnautovic", country: "Austria", position: "forward" },
  { name: "Michael Gregoritsch", country: "Austria", position: "forward" },
  { name: "Sasa Kalajdzic", country: "Austria", position: "forward" },
  // Belgium
  { name: "Thibaut Courtois", country: "Belgium", position: "goalkeeper" },
  { name: "Senne Lammens", country: "Belgium", position: "goalkeeper" },
  { name: "Mike Penders", country: "Belgium", position: "goalkeeper" },
  { name: "Timothy Castagne", country: "Belgium", position: "defender" },
  { name: "Zeno Debast", country: "Belgium", position: "defender" },
  { name: "Maxim De Cuyper", country: "Belgium", position: "defender" },
  { name: "Koni De Winter", country: "Belgium", position: "defender" },
  { name: "Brandon Mechele", country: "Belgium", position: "defender" },
  { name: "Thomas Meunier", country: "Belgium", position: "defender" },
  { name: "Nathan Ngoy", country: "Belgium", position: "defender" },
  { name: "Joaquin Seys", country: "Belgium", position: "defender" },
  { name: "Arthur Theate", country: "Belgium", position: "defender" },
  { name: "Kevin De Bruyne", country: "Belgium", position: "midfielder" },
  { name: "Amadou Onana", country: "Belgium", position: "midfielder" },
  { name: "Nicolas Raskin", country: "Belgium", position: "midfielder" },
  { name: "Youri Tielemans", country: "Belgium", position: "midfielder" },
  { name: "Hans Vanaken", country: "Belgium", position: "midfielder" },
  { name: "Axel Witsel", country: "Belgium", position: "midfielder" },
  { name: "Charles De Ketelaere", country: "Belgium", position: "forward" },
  { name: "Jérémy Doku", country: "Belgium", position: "forward" },
  { name: "Matias Fernandez-Pardo", country: "Belgium", position: "forward" },
  { name: "Romelu Lukaku", country: "Belgium", position: "forward" },
  { name: "Dodi Lukebakio", country: "Belgium", position: "forward" },
  { name: "Diego Moreira", country: "Belgium", position: "forward" },
  { name: "Alexis Saelemaekers", country: "Belgium", position: "forward" },
  { name: "Leandro Trossard", country: "Belgium", position: "forward" },
  // Bosnia-Herzegovina
  { name: "Nikola Vasilj", country: "Bosnia-Herzegovina", position: "goalkeeper" },
  { name: "Martin Zlomislic", country: "Bosnia-Herzegovina", position: "goalkeeper" },
  { name: "Osman Hadzikic", country: "Bosnia-Herzegovina", position: "goalkeeper" },
  { name: "Sead Kolasinac", country: "Bosnia-Herzegovina", position: "defender" },
  { name: "Amar Dedic", country: "Bosnia-Herzegovina", position: "defender" },
  { name: "Nihad Mujakic", country: "Bosnia-Herzegovina", position: "defender" },
  { name: "Nikola Katic", country: "Bosnia-Herzegovina", position: "defender" },
  { name: "Tarik Muharemovic", country: "Bosnia-Herzegovina", position: "defender" },
  { name: "Stjepan Radeljic", country: "Bosnia-Herzegovina", position: "defender" },
  { name: "Dennis Hadzikadunic", country: "Bosnia-Herzegovina", position: "defender" },
  { name: "Nidal Celik", country: "Bosnia-Herzegovina", position: "defender" },
  { name: "Amir Hadziahmetovic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Ivan Sunjic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Ivan Basic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Dzenis Burnic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Ermin Mahmic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Benjamin Tahirovic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Amar Memic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Armin Gigovic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Kerim Alajbegovic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Esmir Bajraktarevic", country: "Bosnia-Herzegovina", position: "midfielder" },
  { name: "Ermedin Demirovic", country: "Bosnia-Herzegovina", position: "forward" },
  { name: "Jovo Lukic", country: "Bosnia-Herzegovina", position: "forward" },
  { name: "Samed Bazdar", country: "Bosnia-Herzegovina", position: "forward" },
  { name: "Haris Tabakovic", country: "Bosnia-Herzegovina", position: "forward" },
  { name: "Edin Dzeko", country: "Bosnia-Herzegovina", position: "forward" },
  // Brazil
  { name: "Alisson", country: "Brazil", position: "goalkeeper" },
  { name: "Éderson", country: "Brazil", position: "goalkeeper" },
  { name: "Weverton", country: "Brazil", position: "goalkeeper" },
  { name: "Alex Sandro", country: "Brazil", position: "defender" },
  { name: "Bremer", country: "Brazil", position: "defender" },
  { name: "Danilo", country: "Brazil", position: "defender" },
  { name: "Douglas Santos", country: "Brazil", position: "defender" },
  { name: "Gabriel Magalhães", country: "Brazil", position: "defender" },
  { name: "Léo Pereira", country: "Brazil", position: "defender" },
  { name: "Marquinhos", country: "Brazil", position: "defender" },
  { name: "Roger Ibañez", country: "Brazil", position: "defender" },
  { name: "Wesley", country: "Brazil", position: "defender" },
  { name: "Bruno Guimarães", country: "Brazil", position: "midfielder" },
  { name: "Casemiro", country: "Brazil", position: "midfielder" },
  { name: "Danilo Santos", country: "Brazil", position: "midfielder" },
  { name: "Fabinho", country: "Brazil", position: "midfielder" },
  { name: "Lucas Paquetá", country: "Brazil", position: "midfielder" },
  { name: "Endrick", country: "Brazil", position: "forward" },
  { name: "Gabriel Martinelli", country: "Brazil", position: "forward" },
  { name: "Igor Thiago", country: "Brazil", position: "forward" },
  { name: "Luiz Henrique", country: "Brazil", position: "forward" },
  { name: "Matheus Cunha", country: "Brazil", position: "forward" },
  { name: "Neymar", country: "Brazil", position: "forward" },
  { name: "Raphinha", country: "Brazil", position: "forward" },
  { name: "Rayan", country: "Brazil", position: "forward" },
  { name: "Vinícius Júnior", country: "Brazil", position: "forward" },
  // Canada
  { name: "Dayne St. Clair", country: "Canada", position: "goalkeeper" },
  { name: "Maxime Crépeau", country: "Canada", position: "goalkeeper" },
  { name: "Owen Goodman", country: "Canada", position: "goalkeeper" },
  { name: "Moïse Bombito", country: "Canada", position: "defender" },
  { name: "Derek Cornelius", country: "Canada", position: "defender" },
  { name: "Alphonso Davies", country: "Canada", position: "defender" },
  { name: "Luc De Fougerolles", country: "Canada", position: "defender" },
  { name: "Alistair Johnston", country: "Canada", position: "defender" },
  { name: "Alfie Jones", country: "Canada", position: "defender" },
  { name: "Richie Laryea", country: "Canada", position: "defender" },
  { name: "Niko Sigur", country: "Canada", position: "defender" },
  { name: "Joel Waterman", country: "Canada", position: "defender" },
  { name: "Ali Ahmed", country: "Canada", position: "midfielder" },
  { name: "Tajon Buchanan", country: "Canada", position: "midfielder" },
  { name: "Mathieu Choinière", country: "Canada", position: "midfielder" },
  { name: "Stephen Eustáquio", country: "Canada", position: "midfielder" },
  { name: "Marcelo Flores", country: "Canada", position: "midfielder" },
  { name: "Ismaël Koné", country: "Canada", position: "midfielder" },
  { name: "Liam Millar", country: "Canada", position: "midfielder" },
  { name: "Jonathan Osorio", country: "Canada", position: "midfielder" },
  { name: "Nathan Saliba", country: "Canada", position: "midfielder" },
  { name: "Jacob Shaffelburg", country: "Canada", position: "midfielder" },
  { name: "Jonathan David", country: "Canada", position: "forward" },
  { name: "Promise David", country: "Canada", position: "forward" },
  { name: "Cyle Larin", country: "Canada", position: "forward" },
  { name: "Tani Oluwaseyi", country: "Canada", position: "forward" },
  // Cape Verde
  { name: "Vozinha", country: "Cape Verde", position: "goalkeeper" },
  { name: "Marcio Rosa", country: "Cape Verde", position: "goalkeeper" },
  { name: "CJ dos Santos", country: "Cape Verde", position: "goalkeeper" },
  { name: "Steven Moreira", country: "Cape Verde", position: "defender" },
  { name: "Wagner Pina", country: "Cape Verde", position: "defender" },
  { name: "Joao Paulo", country: "Cape Verde", position: "defender" },
  { name: "Sidny Lopes Cabral", country: "Cape Verde", position: "defender" },
  { name: "Logan Costa", country: "Cape Verde", position: "defender" },
  { name: "Pico", country: "Cape Verde", position: "defender" },
  { name: "Kelvin Pires", country: "Cape Verde", position: "defender" },
  { name: "Stopira", country: "Cape Verde", position: "defender" },
  { name: "Diney", country: "Cape Verde", position: "defender" },
  { name: "Jamiro Monteiro", country: "Cape Verde", position: "midfielder" },
  { name: "Telmo Arcanjo", country: "Cape Verde", position: "midfielder" },
  { name: "Yannick Semedo", country: "Cape Verde", position: "midfielder" },
  { name: "Laros Duarte", country: "Cape Verde", position: "midfielder" },
  { name: "Deroy Duarte", country: "Cape Verde", position: "midfielder" },
  { name: "Kevin Pina", country: "Cape Verde", position: "midfielder" },
  { name: "Ryan Mendes", country: "Cape Verde", position: "forward" },
  { name: "Willy Semedo", country: "Cape Verde", position: "forward" },
  { name: "Garry Rodrigues", country: "Cape Verde", position: "forward" },
  { name: "Jovane Cabral", country: "Cape Verde", position: "forward" },
  { name: "Nuno da Costa", country: "Cape Verde", position: "forward" },
  { name: "Dailon Livramento", country: "Cape Verde", position: "forward" },
  { name: "Gilson Benchimol", country: "Cape Verde", position: "forward" },
  { name: "Helio Varela", country: "Cape Verde", position: "forward" },
  // Colombia
  { name: "Camilo Vargas", country: "Colombia", position: "goalkeeper" },
  { name: "Alvaro Montero", country: "Colombia", position: "goalkeeper" },
  { name: "David Ospina", country: "Colombia", position: "goalkeeper" },
  { name: "Davinson Sanchez", country: "Colombia", position: "defender" },
  { name: "Jhon Lucumi", country: "Colombia", position: "defender" },
  { name: "Yerry Mina", country: "Colombia", position: "defender" },
  { name: "Willer Ditta", country: "Colombia", position: "defender" },
  { name: "Daniel Munoz", country: "Colombia", position: "defender" },
  { name: "Santiago Arias", country: "Colombia", position: "defender" },
  { name: "Johan Mojica", country: "Colombia", position: "defender" },
  { name: "Deiver Machado", country: "Colombia", position: "defender" },
  { name: "Richard Rios", country: "Colombia", position: "midfielder" },
  { name: "Jefferson Lerma", country: "Colombia", position: "midfielder" },
  { name: "Kevin Castano", country: "Colombia", position: "midfielder" },
  { name: "Gustavo Puerta", country: "Colombia", position: "midfielder" },
  { name: "Jhon Arias", country: "Colombia", position: "midfielder" },
  { name: "Jorge Carrascal", country: "Colombia", position: "midfielder" },
  { name: "Juan Fernando Quintero", country: "Colombia", position: "midfielder" },
  { name: "James Rodriguez", country: "Colombia", position: "midfielder" },
  { name: "Jaminton Campaz", country: "Colombia", position: "midfielder" },
  { name: "Juan Camilo Hernandez", country: "Colombia", position: "forward" },
  { name: "Luis Diaz", country: "Colombia", position: "forward" },
  { name: "Jhon Cordoba", country: "Colombia", position: "forward" },
  { name: "Carlos Andres Gomez", country: "Colombia", position: "forward" },
  { name: "Luis Suarez", country: "Colombia", position: "forward" },
  { name: "Juan Camilo Portilla", country: "Colombia", position: "forward" },
  // Croatia
  { name: "Dominik Livakovic", country: "Croatia", position: "goalkeeper" },
  { name: "Dominik Kotarski", country: "Croatia", position: "goalkeeper" },
  { name: "Ivor Pandur", country: "Croatia", position: "goalkeeper" },
  { name: "Josko Gvardiol", country: "Croatia", position: "defender" },
  { name: "Duje Caleta-Car", country: "Croatia", position: "defender" },
  { name: "Josip Sutalo", country: "Croatia", position: "defender" },
  { name: "Josip Stanisic", country: "Croatia", position: "defender" },
  { name: "Marin Pongracic", country: "Croatia", position: "defender" },
  { name: "Martin Erlic", country: "Croatia", position: "defender" },
  { name: "Luka Vuskovic", country: "Croatia", position: "defender" },
  { name: "Luka Modric", country: "Croatia", position: "midfielder" },
  { name: "Mateo Kovacic", country: "Croatia", position: "midfielder" },
  { name: "Mario Pasalic", country: "Croatia", position: "midfielder" },
  { name: "Nikola Vlasic", country: "Croatia", position: "midfielder" },
  { name: "Luka Sucic", country: "Croatia", position: "midfielder" },
  { name: "Martin Baturina", country: "Croatia", position: "midfielder" },
  { name: "Kristijan Jakic", country: "Croatia", position: "midfielder" },
  { name: "Petar Sucic", country: "Croatia", position: "midfielder" },
  { name: "Nikola Moro", country: "Croatia", position: "midfielder" },
  { name: "Toni Fruk", country: "Croatia", position: "midfielder" },
  { name: "Ivan Perisic", country: "Croatia", position: "forward" },
  { name: "Andrej Kramaric", country: "Croatia", position: "forward" },
  { name: "Ante Budimir", country: "Croatia", position: "forward" },
  { name: "Marco Pasalic", country: "Croatia", position: "forward" },
  { name: "Petar Musa", country: "Croatia", position: "forward" },
  { name: "Igor Matanovic", country: "Croatia", position: "forward" },
  // Curaçao
  { name: "Eloy Room", country: "Curaçao", position: "goalkeeper" },
  { name: "Tyrick Bodak", country: "Curaçao", position: "goalkeeper" },
  { name: "Trevor Doornbusch", country: "Curaçao", position: "goalkeeper" },
  { name: "Riechedly Bazoer", country: "Curaçao", position: "defender" },
  { name: "Joshua Brenet", country: "Curaçao", position: "defender" },
  { name: "Roshon van Eijma", country: "Curaçao", position: "defender" },
  { name: "Sherel Floranus", country: "Curaçao", position: "defender" },
  { name: "Deveron Fonville", country: "Curaçao", position: "defender" },
  { name: "Jurien Gaari", country: "Curaçao", position: "defender" },
  { name: "Armando Obispo", country: "Curaçao", position: "defender" },
  { name: "Shurandy Sambo", country: "Curaçao", position: "defender" },
  { name: "Juninho Bacuna", country: "Curaçao", position: "midfielder" },
  { name: "Leandro Bacuna", country: "Curaçao", position: "midfielder" },
  { name: "Livano Comenencia", country: "Curaçao", position: "midfielder" },
  { name: "Kevin Felida", country: "Curaçao", position: "midfielder" },
  { name: "Ar'jany Martha", country: "Curaçao", position: "midfielder" },
  { name: "Tyrese Noslin", country: "Curaçao", position: "midfielder" },
  { name: "Godfried Roemeratoe", country: "Curaçao", position: "midfielder" },
  { name: "Jeremy Antonisse", country: "Curaçao", position: "forward" },
  { name: "Tahith Chong", country: "Curaçao", position: "forward" },
  { name: "Kenji Gorre", country: "Curaçao", position: "forward" },
  { name: "Sontje Hansen", country: "Curaçao", position: "forward" },
  { name: "Gervane Kastaneer", country: "Curaçao", position: "forward" },
  { name: "Brandley Kuwas", country: "Curaçao", position: "forward" },
  { name: "Jurgen Locadia", country: "Curaçao", position: "forward" },
  { name: "Jearl Margaritha", country: "Curaçao", position: "forward" },
  // Czech Republic
  { name: "Lukas Hornicek", country: "Czech Republic", position: "goalkeeper" },
  { name: "Jan Koutny", country: "Czech Republic", position: "goalkeeper" },
  { name: "Jindreich Stanek", country: "Czech Republic", position: "goalkeeper" },
  { name: "Vladimír Coufal", country: "Czech Republic", position: "defender" },
  { name: "David Douděra", country: "Czech Republic", position: "defender" },
  { name: "Tomáš Holeš", country: "Czech Republic", position: "defender" },
  { name: "Robin Hranáč", country: "Czech Republic", position: "defender" },
  { name: "Štěpán Chaloupek", country: "Czech Republic", position: "defender" },
  { name: "David Jurásek", country: "Czech Republic", position: "defender" },
  { name: "Ladislav Krejčí", country: "Czech Republic", position: "defender" },
  { name: "Jaroslav Zelený", country: "Czech Republic", position: "defender" },
  { name: "David Zima", country: "Czech Republic", position: "defender" },
  { name: "Lukás Cerv", country: "Czech Republic", position: "midfielder" },
  { name: "Vladimir Darida", country: "Czech Republic", position: "midfielder" },
  { name: "Lukás Provod", country: "Czech Republic", position: "midfielder" },
  { name: "Michal Sadílek", country: "Czech Republic", position: "midfielder" },
  { name: "Hugo Sochůrek", country: "Czech Republic", position: "midfielder" },
  { name: "Alexandr Sojka", country: "Czech Republic", position: "midfielder" },
  { name: "Tomáš Souček", country: "Czech Republic", position: "midfielder" },
  { name: "Adam Hložek", country: "Czech Republic", position: "forward" },
  { name: "Tomáš Chorý", country: "Czech Republic", position: "forward" },
  { name: "Mojmír Chytil", country: "Czech Republic", position: "forward" },
  { name: "Jan Kuchta", country: "Czech Republic", position: "forward" },
  { name: "Patrik Schick", country: "Czech Republic", position: "forward" },
  { name: "Matej Vydra", country: "Czech Republic", position: "forward" },
  { name: "Denis Višinský", country: "Czech Republic", position: "forward" },
  // DR Congo
  { name: "Matthieu Epolo", country: "DR Congo", position: "goalkeeper" },
  { name: "Timothy Fayulu", country: "DR Congo", position: "goalkeeper" },
  { name: "Lionel Mpasi", country: "DR Congo", position: "goalkeeper" },
  { name: "Dylan Batubinsika", country: "DR Congo", position: "defender" },
  { name: "Rocky Bushiri", country: "DR Congo", position: "defender" },
  { name: "Steve Kapuadi", country: "DR Congo", position: "defender" },
  { name: "Joris Kayembe", country: "DR Congo", position: "defender" },
  { name: "Gedeon Kalulu", country: "DR Congo", position: "defender" },
  { name: "Arthur Masuaku", country: "DR Congo", position: "defender" },
  { name: "Chancel Mbemba", country: "DR Congo", position: "defender" },
  { name: "Axel Tuanzebe", country: "DR Congo", position: "defender" },
  { name: "Aaron Wan-Bissaka", country: "DR Congo", position: "defender" },
  { name: "Brian Cipenga", country: "DR Congo", position: "midfielder" },
  { name: "Meshack Elia", country: "DR Congo", position: "midfielder" },
  { name: "Gael Kakuta", country: "DR Congo", position: "midfielder" },
  { name: "Edo Kayembe", country: "DR Congo", position: "midfielder" },
  { name: "Nathanael Mbuku", country: "DR Congo", position: "midfielder" },
  { name: "Samuel Moutoussamy", country: "DR Congo", position: "midfielder" },
  { name: "Ngal'ayel Mukau", country: "DR Congo", position: "midfielder" },
  { name: "Charles Pickel", country: "DR Congo", position: "midfielder" },
  { name: "Noah Sadiki", country: "DR Congo", position: "midfielder" },
  { name: "Aaron Tshibola", country: "DR Congo", position: "midfielder" },
  { name: "Cedric Bakambu", country: "DR Congo", position: "forward" },
  { name: "Simon Banza", country: "DR Congo", position: "forward" },
  { name: "Fiston Mayele", country: "DR Congo", position: "forward" },
  { name: "Yoane Wissa", country: "DR Congo", position: "forward" },
  { name: "Theo Bongonda", country: "DR Congo", position: "forward" },
  // Ecuador
  { name: "Hernán Galíndez", country: "Ecuador", position: "goalkeeper" },
  { name: "Moisés Ramírez", country: "Ecuador", position: "goalkeeper" },
  { name: "Gonzalo Valle", country: "Ecuador", position: "goalkeeper" },
  { name: "Willian Pacho", country: "Ecuador", position: "defender" },
  { name: "Piero Hincapié", country: "Ecuador", position: "defender" },
  { name: "Joel Ordóñez", country: "Ecuador", position: "defender" },
  { name: "Félix Torres", country: "Ecuador", position: "defender" },
  { name: "Pervis Estupiñán", country: "Ecuador", position: "defender" },
  { name: "Yaimar Medina", country: "Ecuador", position: "defender" },
  { name: "Ángelo Preciado", country: "Ecuador", position: "defender" },
  { name: "Jackson Porozo", country: "Ecuador", position: "defender" },
  { name: "Alan Minda", country: "Ecuador", position: "midfielder" },
  { name: "Moisés Caicedo", country: "Ecuador", position: "midfielder" },
  { name: "Jordy Alcivar", country: "Ecuador", position: "midfielder" },
  { name: "Denil Castillo", country: "Ecuador", position: "midfielder" },
  { name: "John Yeboah", country: "Ecuador", position: "midfielder" },
  { name: "Alan Franco", country: "Ecuador", position: "midfielder" },
  { name: "Pedro Vite", country: "Ecuador", position: "midfielder" },
  { name: "Kendry Páez", country: "Ecuador", position: "midfielder" },
  { name: "Nilson Angulo", country: "Ecuador", position: "midfielder" },
  { name: "Gonzalo Plata", country: "Ecuador", position: "midfielder" },
  { name: "Kevin Rodríguez", country: "Ecuador", position: "forward" },
  { name: "Anthony Valencia", country: "Ecuador", position: "forward" },
  { name: "Enner Valencia", country: "Ecuador", position: "forward" },
  { name: "Jordy Caicedo", country: "Ecuador", position: "forward" },
  { name: "Jeremy Arévalo", country: "Ecuador", position: "forward" },
  // Egypt
  { name: "Mohamed El Shenawy", country: "Egypt", position: "goalkeeper" },
  { name: "Mostafa Shobeir", country: "Egypt", position: "goalkeeper" },
  { name: "El Mahdy Soliman", country: "Egypt", position: "goalkeeper" },
  { name: "Mohamed Alaa", country: "Egypt", position: "goalkeeper" },
  { name: "Mohamed Hany", country: "Egypt", position: "defender" },
  { name: "Tarek Alaa", country: "Egypt", position: "defender" },
  { name: "Hamdy Fathy", country: "Egypt", position: "defender" },
  { name: "Ramy Rabia", country: "Egypt", position: "defender" },
  { name: "Yasser Ibrahim", country: "Egypt", position: "defender" },
  { name: "Hossam Abdelmaguid", country: "Egypt", position: "defender" },
  { name: "Mohamed Abdelmonem", country: "Egypt", position: "defender" },
  { name: "Ahmed Fatouh", country: "Egypt", position: "defender" },
  { name: "Karim Hafez", country: "Egypt", position: "defender" },
  { name: "Marwan Attia", country: "Egypt", position: "midfielder" },
  { name: "Mohanad Lasheen", country: "Egypt", position: "midfielder" },
  { name: "Nabil Emad", country: "Egypt", position: "midfielder" },
  { name: "Mahmoud Saber", country: "Egypt", position: "midfielder" },
  { name: "Ahmed Zizo", country: "Egypt", position: "midfielder" },
  { name: "Emam Ashour", country: "Egypt", position: "midfielder" },
  { name: "Mostafa Ziko", country: "Egypt", position: "midfielder" },
  { name: "Mahmoud Trezeguet", country: "Egypt", position: "midfielder" },
  { name: "Ibrahim Adel", country: "Egypt", position: "midfielder" },
  { name: "Haissem Hassan", country: "Egypt", position: "midfielder" },
  { name: "Omar Marmoush", country: "Egypt", position: "forward" },
  { name: "Mohamed Salah", country: "Egypt", position: "forward" },
  { name: "Hamza Abdelkarim", country: "Egypt", position: "forward" },
  // England
  { name: "Jordan Pickford", country: "England", position: "goalkeeper" },
  { name: "Dean Henderson", country: "England", position: "goalkeeper" },
  { name: "James Trafford", country: "England", position: "goalkeeper" },
  { name: "Reece James", country: "England", position: "defender" },
  { name: "Ezri Konsa", country: "England", position: "defender" },
  { name: "Jarell Quansah", country: "England", position: "defender" },
  { name: "John Stones", country: "England", position: "defender" },
  { name: "Marc Guehi", country: "England", position: "defender" },
  { name: "Dan Burn", country: "England", position: "defender" },
  { name: "Nico O'Reilly", country: "England", position: "defender" },
  { name: "Djed Spence", country: "England", position: "defender" },
  { name: "Tino Livramento", country: "England", position: "defender" },
  { name: "Declan Rice", country: "England", position: "midfielder" },
  { name: "Elliot Anderson", country: "England", position: "midfielder" },
  { name: "Kobbie Mainoo", country: "England", position: "midfielder" },
  { name: "Jordan Henderson", country: "England", position: "midfielder" },
  { name: "Morgan Rogers", country: "England", position: "midfielder" },
  { name: "Jude Bellingham", country: "England", position: "midfielder" },
  { name: "Eberechi Eze", country: "England", position: "midfielder" },
  { name: "Harry Kane", country: "England", position: "forward" },
  { name: "Ivan Toney", country: "England", position: "forward" },
  { name: "Ollie Watkins", country: "England", position: "forward" },
  { name: "Bukayo Saka", country: "England", position: "forward" },
  { name: "Marcus Rashford", country: "England", position: "forward" },
  { name: "Anthony Gordon", country: "England", position: "forward" },
  { name: "Noni Madueke", country: "England", position: "forward" },
  // France
  { name: "Mike Maignan", country: "France", position: "goalkeeper" },
  { name: "Robin Risser", country: "France", position: "goalkeeper" },
  { name: "Brice Samba", country: "France", position: "goalkeeper" },
  { name: "Lucas Digne", country: "France", position: "defender" },
  { name: "Malo Gusto", country: "France", position: "defender" },
  { name: "Lucas Hernández", country: "France", position: "defender" },
  { name: "Theo Hernández", country: "France", position: "defender" },
  { name: "Ibrahima Konaté", country: "France", position: "defender" },
  { name: "Jules Koundé", country: "France", position: "defender" },
  { name: "Maxence Lacroix", country: "France", position: "defender" },
  { name: "William Saliba", country: "France", position: "defender" },
  { name: "Dayot Upamecano", country: "France", position: "defender" },
  { name: "N'Golo Kanté", country: "France", position: "midfielder" },
  { name: "Manu Koné", country: "France", position: "midfielder" },
  { name: "Adrien Rabiot", country: "France", position: "midfielder" },
  { name: "Aurélien Tchouaméni", country: "France", position: "midfielder" },
  { name: "Warren Zaïre-Emery", country: "France", position: "midfielder" },
  { name: "Maghnes Akliouche", country: "France", position: "forward" },
  { name: "Bradley Barcola", country: "France", position: "forward" },
  { name: "Rayan Cherki", country: "France", position: "forward" },
  { name: "Ousmane Dembélé", country: "France", position: "forward" },
  { name: "Désiré Doué", country: "France", position: "forward" },
  { name: "Jean-Philippe Mateta", country: "France", position: "forward" },
  { name: "Kylian Mbappé", country: "France", position: "forward" },
  { name: "Michael Olise", country: "France", position: "forward" },
  { name: "Marcus Thuram", country: "France", position: "forward" },
  // Germany
  { name: "Oliver Baumann", country: "Germany", position: "goalkeeper" },
  { name: "Manuel Neuer", country: "Germany", position: "goalkeeper" },
  { name: "Alexander Nübel", country: "Germany", position: "goalkeeper" },
  { name: "Waldemar Anton", country: "Germany", position: "defender" },
  { name: "Nathaniel Brown", country: "Germany", position: "defender" },
  { name: "David Raum", country: "Germany", position: "defender" },
  { name: "Antonio Rüdiger", country: "Germany", position: "defender" },
  { name: "Nico Schlotterbeck", country: "Germany", position: "defender" },
  { name: "Jonathan Tah", country: "Germany", position: "defender" },
  { name: "Malick Thiaw", country: "Germany", position: "defender" },
  { name: "Pascal Gross", country: "Germany", position: "midfielder" },
  { name: "Joshua Kimmich", country: "Germany", position: "midfielder" },
  { name: "Felix Nmecha", country: "Germany", position: "midfielder" },
  { name: "Aleksandar Pavlovic", country: "Germany", position: "midfielder" },
  { name: "Angelo Stiller", country: "Germany", position: "midfielder" },
  { name: "Leon Goretzka", country: "Germany", position: "midfielder" },
  { name: "Florian Wirtz", country: "Germany", position: "midfielder" },
  { name: "Jamie Leweling", country: "Germany", position: "midfielder" },
  { name: "Maximilian Beier", country: "Germany", position: "forward" },
  { name: "Kai Havertz", country: "Germany", position: "forward" },
  { name: "Lennart Karl", country: "Germany", position: "forward" },
  { name: "Jamal Musiala", country: "Germany", position: "forward" },
  { name: "Leroy Sané", country: "Germany", position: "forward" },
  { name: "Deniz Undav", country: "Germany", position: "forward" },
  { name: "Nick Woltemade", country: "Germany", position: "forward" },
  // Ghana
  { name: "Lawrence Ati-Zigi", country: "Ghana", position: "goalkeeper" },
  { name: "Benjamin Asare", country: "Ghana", position: "goalkeeper" },
  { name: "Joseph Anang", country: "Ghana", position: "goalkeeper" },
  { name: "Abdul Rahman Baba", country: "Ghana", position: "defender" },
  { name: "Gideon Mensah", country: "Ghana", position: "defender" },
  { name: "Alidu Seidu", country: "Ghana", position: "defender" },
  { name: "Jerome Opoku", country: "Ghana", position: "defender" },
  { name: "Jonas Adjetey", country: "Ghana", position: "defender" },
  { name: "Abdul Mumin", country: "Ghana", position: "defender" },
  { name: "Kojo Oppong Peprah", country: "Ghana", position: "defender" },
  { name: "Marvin Senaya", country: "Ghana", position: "defender" },
  { name: "Derrick Luckassen", country: "Ghana", position: "defender" },
  { name: "Thomas Partey", country: "Ghana", position: "midfielder" },
  { name: "Abdul Fatawu Issahaku", country: "Ghana", position: "midfielder" },
  { name: "Elisha Owusu", country: "Ghana", position: "midfielder" },
  { name: "Caleb Yirenkyi", country: "Ghana", position: "midfielder" },
  { name: "Kwasi Sibo", country: "Ghana", position: "midfielder" },
  { name: "Augustine Boakye", country: "Ghana", position: "midfielder" },
  { name: "Kamaldeen Sulemana", country: "Ghana", position: "midfielder" },
  { name: "Jordan Ayew", country: "Ghana", position: "forward" },
  { name: "Antoine Semenyo", country: "Ghana", position: "forward" },
  { name: "Inaki Williams", country: "Ghana", position: "forward" },
  { name: "Ernest Nuamah", country: "Ghana", position: "forward" },
  { name: "Christopher Bonsu Baah", country: "Ghana", position: "forward" },
  { name: "Brandon Thomas-Asante", country: "Ghana", position: "forward" },
  { name: "Prince Kwabena Adu", country: "Ghana", position: "forward" },
  // Haiti
  { name: "Johny Placide", country: "Haiti", position: "goalkeeper" },
  { name: "Alexandre Pierre", country: "Haiti", position: "goalkeeper" },
  { name: "Josue Duverger", country: "Haiti", position: "goalkeeper" },
  { name: "Carlens Arcus", country: "Haiti", position: "defender" },
  { name: "Wilguens Paugain", country: "Haiti", position: "defender" },
  { name: "Duke Lacroix", country: "Haiti", position: "defender" },
  { name: "Martin Expérience", country: "Haiti", position: "defender" },
  { name: "Jean-Kévin Duverne", country: "Haiti", position: "defender" },
  { name: "Ricardo Adé", country: "Haiti", position: "defender" },
  { name: "Hannes Delcroix", country: "Haiti", position: "defender" },
  { name: "Keeto Thermoncy", country: "Haiti", position: "defender" },
  { name: "Carl Fred Sainté", country: "Haiti", position: "midfielder" },
  { name: "Leverton Pierre", country: "Haiti", position: "midfielder" },
  { name: "Danley Jean Jacques", country: "Haiti", position: "midfielder" },
  { name: "Jean-Ricner Bellegarde", country: "Haiti", position: "midfielder" },
  { name: "Woodensky Pierre", country: "Haiti", position: "midfielder" },
  { name: "Dominique Simon", country: "Haiti", position: "midfielder" },
  { name: "Don Deedson Louicius", country: "Haiti", position: "forward" },
  { name: "Josué Casimir", country: "Haiti", position: "forward" },
  { name: "Derrick Etienne", country: "Haiti", position: "forward" },
  { name: "Ruben Providence", country: "Haiti", position: "forward" },
  { name: "Duckens Nazon", country: "Haiti", position: "forward" },
  { name: "Frantzdy Pierrot", country: "Haiti", position: "forward" },
  { name: "Wilson Isidor", country: "Haiti", position: "forward" },
  { name: "Yassin Fortuné", country: "Haiti", position: "forward" },
  { name: "Lenny Joseph", country: "Haiti", position: "forward" },
  // Iran
  { name: "Alireza Beiranvand", country: "Iran", position: "goalkeeper" },
  { name: "Hossein Hosseini", country: "Iran", position: "goalkeeper" },
  { name: "Payam Niazmand", country: "Iran", position: "goalkeeper" },
  { name: "Danial Eiri", country: "Iran", position: "defender" },
  { name: "Ehsan Hajsafi", country: "Iran", position: "defender" },
  { name: "Saleh Hardani", country: "Iran", position: "defender" },
  { name: "Hossein Kanaani", country: "Iran", position: "defender" },
  { name: "Shoka Khalilzadeh", country: "Iran", position: "defender" },
  { name: "Milad Mohammadi", country: "Iran", position: "defender" },
  { name: "Ali Nemati", country: "Iran", position: "defender" },
  { name: "Omid Noorafkan", country: "Iran", position: "defender" },
  { name: "Ramin Rezaeian", country: "Iran", position: "defender" },
  { name: "Rouzbeh Cheshmi", country: "Iran", position: "midfielder" },
  { name: "Saeid Ezatolahi", country: "Iran", position: "midfielder" },
  { name: "Mehdi Ghaedi", country: "Iran", position: "midfielder" },
  { name: "Saman Ghoddos", country: "Iran", position: "midfielder" },
  { name: "Mohammad Ghorbani", country: "Iran", position: "midfielder" },
  { name: "Alireza Jahanbakhsh", country: "Iran", position: "midfielder" },
  { name: "Mohammad Mohebi", country: "Iran", position: "midfielder" },
  { name: "Amir Mohammad Razzaghinia", country: "Iran", position: "midfielder" },
  { name: "Mehdi Torabi", country: "Iran", position: "midfielder" },
  { name: "Aria Yousefi", country: "Iran", position: "midfielder" },
  { name: "Ali Alipour", country: "Iran", position: "forward" },
  { name: "Dennis Dargahi", country: "Iran", position: "forward" },
  { name: "Amirhossein Hosseinzadeh", country: "Iran", position: "forward" },
  { name: "Amirhossein Mahmoudi", country: "Iran", position: "forward" },
  { name: "Mehdi Taremi", country: "Iran", position: "forward" },
  // Iraq
  { name: "Fahad Talib", country: "Iraq", position: "goalkeeper" },
  { name: "Jalal Hassan", country: "Iraq", position: "goalkeeper" },
  { name: "Ahmed Basil", country: "Iraq", position: "goalkeeper" },
  { name: "Hussein Ali", country: "Iraq", position: "defender" },
  { name: "Manaf Younis", country: "Iraq", position: "defender" },
  { name: "Zaid Tahseen", country: "Iraq", position: "defender" },
  { name: "Rebin Sulaka", country: "Iraq", position: "defender" },
  { name: "Akam Hashem", country: "Iraq", position: "defender" },
  { name: "Merchas Doski", country: "Iraq", position: "defender" },
  { name: "Ahmed Yahya", country: "Iraq", position: "defender" },
  { name: "Zaid Ismail", country: "Iraq", position: "defender" },
  { name: "Frans Putros", country: "Iraq", position: "defender" },
  { name: "Mustafa Saadoon", country: "Iraq", position: "defender" },
  { name: "Amir Al-Ammari", country: "Iraq", position: "midfielder" },
  { name: "Kevin Yakob", country: "Iraq", position: "midfielder" },
  { name: "Zidane Iqbal", country: "Iraq", position: "midfielder" },
  { name: "Aimar Sher", country: "Iraq", position: "midfielder" },
  { name: "Ibrahim Bayesh", country: "Iraq", position: "midfielder" },
  { name: "Ahmed Qasem", country: "Iraq", position: "midfielder" },
  { name: "Youssef Amyn", country: "Iraq", position: "midfielder" },
  { name: "Marko Farji", country: "Iraq", position: "midfielder" },
  { name: "Ali Jassim", country: "Iraq", position: "forward" },
  { name: "Ali Al-Hamadi", country: "Iraq", position: "forward" },
  { name: "Ali Yousef", country: "Iraq", position: "forward" },
  { name: "Aymen Hussein", country: "Iraq", position: "forward" },
  { name: "Mohanad Ali", country: "Iraq", position: "forward" },
  // Ivory Coast
  { name: "Yahia Fofana", country: "Ivory Coast", position: "goalkeeper" },
  { name: "Mohamed Koné", country: "Ivory Coast", position: "goalkeeper" },
  { name: "Alban Lafont", country: "Ivory Coast", position: "goalkeeper" },
  { name: "Emmanuel Agbadou", country: "Ivory Coast", position: "defender" },
  { name: "Clément Akpa", country: "Ivory Coast", position: "defender" },
  { name: "Ousmane Diomande", country: "Ivory Coast", position: "defender" },
  { name: "Guela Doué", country: "Ivory Coast", position: "defender" },
  { name: "Ghislain Konan", country: "Ivory Coast", position: "defender" },
  { name: "Odilon Kossounou", country: "Ivory Coast", position: "defender" },
  { name: "Evan Ndicka", country: "Ivory Coast", position: "defender" },
  { name: "Wilfried Singo", country: "Ivory Coast", position: "defender" },
  { name: "Seko Fofana", country: "Ivory Coast", position: "midfielder" },
  { name: "Parfait Guiagon", country: "Ivory Coast", position: "midfielder" },
  { name: "Franck Kessié", country: "Ivory Coast", position: "midfielder" },
  { name: "Christ Inao Oulaï", country: "Ivory Coast", position: "midfielder" },
  { name: "Ibrahim Sangaré", country: "Ivory Coast", position: "midfielder" },
  { name: "Jean Michaël Seri", country: "Ivory Coast", position: "midfielder" },
  { name: "Simon Adingra", country: "Ivory Coast", position: "forward" },
  { name: "Ange-Yoan Bonny", country: "Ivory Coast", position: "forward" },
  { name: "Amad Diallo", country: "Ivory Coast", position: "forward" },
  { name: "Oumar Diakité", country: "Ivory Coast", position: "forward" },
  { name: "Yan Diomande", country: "Ivory Coast", position: "forward" },
  { name: "Evann Guessand", country: "Ivory Coast", position: "forward" },
  { name: "Nicolas Pépé", country: "Ivory Coast", position: "forward" },
  { name: "Bazoumana Touré", country: "Ivory Coast", position: "forward" },
  { name: "Elye Wahi", country: "Ivory Coast", position: "forward" },
  // Japan
  { name: "Zion Suzuki", country: "Japan", position: "goalkeeper" },
  { name: "Keisuke Osako", country: "Japan", position: "goalkeeper" },
  { name: "Tomoki Hayakawa", country: "Japan", position: "goalkeeper" },
  { name: "Yūto Nagatomo", country: "Japan", position: "defender" },
  { name: "Shogo Taniguchi", country: "Japan", position: "defender" },
  { name: "Ko Itakura", country: "Japan", position: "defender" },
  { name: "Tsuyoshi Watanabe", country: "Japan", position: "defender" },
  { name: "Takehiro Tomiyasu", country: "Japan", position: "defender" },
  { name: "Hiroki Ito", country: "Japan", position: "defender" },
  { name: "Ayumu Seko", country: "Japan", position: "defender" },
  { name: "Yukinari Sugawara", country: "Japan", position: "defender" },
  { name: "Junnosuke Suzuki", country: "Japan", position: "midfielder" },
  { name: "Wataru Endo", country: "Japan", position: "midfielder" },
  { name: "Junya Ito", country: "Japan", position: "midfielder" },
  { name: "Daichi Kamada", country: "Japan", position: "midfielder" },
  { name: "Ritsu Doan", country: "Japan", position: "midfielder" },
  { name: "Ao Tanaka", country: "Japan", position: "midfielder" },
  { name: "Keito Nakamura", country: "Japan", position: "midfielder" },
  { name: "Kaishu Sano", country: "Japan", position: "midfielder" },
  { name: "Takefusa Kubo", country: "Japan", position: "midfielder" },
  { name: "Yuito Suzuki", country: "Japan", position: "midfielder" },
  { name: "Koki Ogawa", country: "Japan", position: "forward" },
  { name: "Daizen Maeda", country: "Japan", position: "forward" },
  { name: "Ayase Ueda", country: "Japan", position: "forward" },
  { name: "Kento Shiogai", country: "Japan", position: "forward" },
  { name: "Keisuke Goto", country: "Japan", position: "forward" },
  // Jordan
  { name: "Yazid Abu Laila", country: "Jordan", position: "goalkeeper" },
  { name: "Nour Bani Attiah", country: "Jordan", position: "goalkeeper" },
  { name: "Abdallah Al-Fakhouri", country: "Jordan", position: "goalkeeper" },
  { name: "Mohammad Abu Hashish", country: "Jordan", position: "defender" },
  { name: "Abdallah Nasib", country: "Jordan", position: "defender" },
  { name: "Husam Abu Dahab", country: "Jordan", position: "defender" },
  { name: "Yazan Al-Arab", country: "Jordan", position: "defender" },
  { name: "Mohammad Abu Al-Nadi", country: "Jordan", position: "defender" },
  { name: "Saleem Obaid", country: "Jordan", position: "defender" },
  { name: "Saed Al-Rosan", country: "Jordan", position: "defender" },
  { name: "Ehsan Haddad", country: "Jordan", position: "defender" },
  { name: "Anas Badawi", country: "Jordan", position: "defender" },
  { name: "Amer Jamous", country: "Jordan", position: "midfielder" },
  { name: "Noor Al-Rawabdeh", country: "Jordan", position: "midfielder" },
  { name: "Rajaei Ayed", country: "Jordan", position: "midfielder" },
  { name: "Ibrahim Sadeh", country: "Jordan", position: "midfielder" },
  { name: "Mohannad Abu Taha", country: "Jordan", position: "midfielder" },
  { name: "Nizar Al-Rashdan", country: "Jordan", position: "midfielder" },
  { name: "Mohammad Al-Dawoud", country: "Jordan", position: "midfielder" },
  { name: "Yousef Qashi", country: "Jordan", position: "midfielder" },
  { name: "Mohammad Taha", country: "Jordan", position: "midfielder" },
  { name: "Mohammad Abu Zrayq", country: "Jordan", position: "forward" },
  { name: "Ali Olwan", country: "Jordan", position: "forward" },
  { name: "Musa Al-Taamari", country: "Jordan", position: "forward" },
  { name: "Odeh Al-Fakhouri", country: "Jordan", position: "forward" },
  { name: "Mahmoud Mardi", country: "Jordan", position: "forward" },
  { name: "Ibrahim Sabra", country: "Jordan", position: "forward" },
  { name: "Ali Azaizeh", country: "Jordan", position: "forward" },
  // Mexico
  { name: "Carlos Acevedo", country: "Mexico", position: "goalkeeper" },
  { name: "Guillermo Ochoa", country: "Mexico", position: "goalkeeper" },
  { name: "Raúl Rangel", country: "Mexico", position: "goalkeeper" },
  { name: "Jesús Gallardo", country: "Mexico", position: "defender" },
  { name: "Israel Reyes", country: "Mexico", position: "defender" },
  { name: "César Montes", country: "Mexico", position: "defender" },
  { name: "Jorge Sánchez", country: "Mexico", position: "defender" },
  { name: "Johan Vásquez", country: "Mexico", position: "defender" },
  { name: "Mateo Chávez", country: "Mexico", position: "defender" },
  { name: "Gilberto Mora", country: "Mexico", position: "midfielder" },
  { name: "Edson Álvarez", country: "Mexico", position: "midfielder" },
  { name: "Orbelín Pineda", country: "Mexico", position: "midfielder" },
  { name: "Luis Romo", country: "Mexico", position: "midfielder" },
  { name: "Brian Gutiérrez", country: "Mexico", position: "midfielder" },
  { name: "Obed Vargas", country: "Mexico", position: "midfielder" },
  { name: "César Huerta", country: "Mexico", position: "midfielder" },
  { name: "Luis Chávez", country: "Mexico", position: "midfielder" },
  { name: "Erik Lira", country: "Mexico", position: "midfielder" },
  { name: "Álvaro Fidalgo", country: "Mexico", position: "midfielder" },
  { name: "Roberto Alvarado", country: "Mexico", position: "midfielder" },
  { name: "Armando González", country: "Mexico", position: "forward" },
  { name: "Raúl Jiménez", country: "Mexico", position: "forward" },
  { name: "Julián Quiñones", country: "Mexico", position: "forward" },
  { name: "Santiago Gimenez", country: "Mexico", position: "forward" },
  { name: "Guillermo Martínez", country: "Mexico", position: "forward" },
  { name: "Alexis Vega", country: "Mexico", position: "forward" },
  // Morocco
  { name: "Yassine Bounou", country: "Morocco", position: "goalkeeper" },
  { name: "Munir El Kajoui", country: "Morocco", position: "goalkeeper" },
  { name: "Reda Tagnaouti", country: "Morocco", position: "goalkeeper" },
  { name: "Noussair Mazraoui", country: "Morocco", position: "defender" },
  { name: "Anass Salah-Eddine", country: "Morocco", position: "defender" },
  { name: "Youssef Belammari", country: "Morocco", position: "defender" },
  { name: "Achraf Hakimi", country: "Morocco", position: "defender" },
  { name: "Zakaria El Ouahdi", country: "Morocco", position: "defender" },
  { name: "Chadi Riad", country: "Morocco", position: "defender" },
  { name: "Nayef Aguerd", country: "Morocco", position: "defender" },
  { name: "Redouane Halhal", country: "Morocco", position: "defender" },
  { name: "Issa Diop", country: "Morocco", position: "defender" },
  { name: "Samir El Mourabet", country: "Morocco", position: "midfielder" },
  { name: "Ayyoub Bouaddi", country: "Morocco", position: "midfielder" },
  { name: "Neil El Aynaoui", country: "Morocco", position: "midfielder" },
  { name: "Sofyan Amrabat", country: "Morocco", position: "midfielder" },
  { name: "Azzedine Ounahi", country: "Morocco", position: "midfielder" },
  { name: "Bilal El Khannouss", country: "Morocco", position: "midfielder" },
  { name: "Ismael Saibari", country: "Morocco", position: "midfielder" },
  { name: "Abde Ezzalzouli", country: "Morocco", position: "forward" },
  { name: "Chemsdine Talbi", country: "Morocco", position: "forward" },
  { name: "Soufiane Rahimi", country: "Morocco", position: "forward" },
  { name: "Ayoub El Kaabi", country: "Morocco", position: "forward" },
  { name: "Brahim Díaz", country: "Morocco", position: "forward" },
  { name: "Gessime Yassine", country: "Morocco", position: "forward" },
  { name: "Ayoube Amaimouni", country: "Morocco", position: "forward" },
  // Netherlands
  { name: "Mark Flekken", country: "Netherlands", position: "goalkeeper" },
  { name: "Robin Roefs", country: "Netherlands", position: "goalkeeper" },
  { name: "Bart Verbruggen", country: "Netherlands", position: "goalkeeper" },
  { name: "Nathan Aké", country: "Netherlands", position: "defender" },
  { name: "Denzel Dumfries", country: "Netherlands", position: "defender" },
  { name: "Jorrel Hato", country: "Netherlands", position: "defender" },
  { name: "Jurriën Timber", country: "Netherlands", position: "defender" },
  { name: "Jan Paul van Hecke", country: "Netherlands", position: "defender" },
  { name: "Micky van de Ven", country: "Netherlands", position: "defender" },
  { name: "Virgil van Dijk", country: "Netherlands", position: "defender" },
  { name: "Frenkie de Jong", country: "Netherlands", position: "midfielder" },
  { name: "Marten de Roon", country: "Netherlands", position: "midfielder" },
  { name: "Ryan Gravenberch", country: "Netherlands", position: "midfielder" },
  { name: "Teun Koopmeiners", country: "Netherlands", position: "midfielder" },
  { name: "Tijjani Reijnders", country: "Netherlands", position: "midfielder" },
  { name: "Guus Til", country: "Netherlands", position: "midfielder" },
  { name: "Quinten Timber", country: "Netherlands", position: "midfielder" },
  { name: "Mats Wieffer", country: "Netherlands", position: "midfielder" },
  { name: "Brian Brobbey", country: "Netherlands", position: "forward" },
  { name: "Memphis Depay", country: "Netherlands", position: "forward" },
  { name: "Cody Gakpo", country: "Netherlands", position: "forward" },
  { name: "Justin Kluivert", country: "Netherlands", position: "forward" },
  { name: "Noa Lang", country: "Netherlands", position: "forward" },
  { name: "Donyell Malen", country: "Netherlands", position: "forward" },
  { name: "Crysencio Summerville", country: "Netherlands", position: "forward" },
  { name: "Wout Weghorst", country: "Netherlands", position: "forward" },
  // New Zealand
  { name: "Max Crocombe", country: "New Zealand", position: "goalkeeper" },
  { name: "Alex Paulsen", country: "New Zealand", position: "goalkeeper" },
  { name: "Michael Woud", country: "New Zealand", position: "goalkeeper" },
  { name: "Tim Payne", country: "New Zealand", position: "defender" },
  { name: "Francis De Vries", country: "New Zealand", position: "defender" },
  { name: "Tyler Bindon", country: "New Zealand", position: "defender" },
  { name: "Michael Boxall", country: "New Zealand", position: "defender" },
  { name: "Liberato Cacace", country: "New Zealand", position: "defender" },
  { name: "Nando Pijnaker", country: "New Zealand", position: "defender" },
  { name: "Finn Surman", country: "New Zealand", position: "defender" },
  { name: "Callan Elliot", country: "New Zealand", position: "defender" },
  { name: "Tommy Smith", country: "New Zealand", position: "defender" },
  { name: "Joe Bell", country: "New Zealand", position: "midfielder" },
  { name: "Matt Garbett", country: "New Zealand", position: "midfielder" },
  { name: "Marko Stamenic", country: "New Zealand", position: "midfielder" },
  { name: "Sarpreet Singh", country: "New Zealand", position: "midfielder" },
  { name: "Alex Rufer", country: "New Zealand", position: "midfielder" },
  { name: "Ryan Thomas", country: "New Zealand", position: "midfielder" },
  { name: "Chris Wood", country: "New Zealand", position: "forward" },
  { name: "Eli Just", country: "New Zealand", position: "forward" },
  { name: "Kosta Barbarouses", country: "New Zealand", position: "forward" },
  { name: "Ben Waine", country: "New Zealand", position: "forward" },
  { name: "Ben Old", country: "New Zealand", position: "forward" },
  { name: "Callum McCowatt", country: "New Zealand", position: "forward" },
  { name: "Jesse Randall", country: "New Zealand", position: "forward" },
  { name: "Lachlan Bayliss", country: "New Zealand", position: "forward" },
  // Norway
  { name: "Orjan Nyland", country: "Norway", position: "goalkeeper" },
  { name: "Egil Selvik", country: "Norway", position: "goalkeeper" },
  { name: "Sander Tangvik", country: "Norway", position: "goalkeeper" },
  { name: "Kristoffer Ajer", country: "Norway", position: "defender" },
  { name: "Fredrik Bjorkan", country: "Norway", position: "defender" },
  { name: "Henrik Falchener", country: "Norway", position: "defender" },
  { name: "Sondre Langas", country: "Norway", position: "defender" },
  { name: "Torbjorn Heggem", country: "Norway", position: "defender" },
  { name: "Marcus Holmgren Pedersen", country: "Norway", position: "defender" },
  { name: "Julian Ryerson", country: "Norway", position: "defender" },
  { name: "David Moller Wolfe", country: "Norway", position: "defender" },
  { name: "Leo Ostigard", country: "Norway", position: "defender" },
  { name: "Thelonious Aasgaard", country: "Norway", position: "midfielder" },
  { name: "Fredrik Aursnes", country: "Norway", position: "midfielder" },
  { name: "Patrick Berg", country: "Norway", position: "midfielder" },
  { name: "Sander Berge", country: "Norway", position: "midfielder" },
  { name: "Jens Petter Hauge", country: "Norway", position: "midfielder" },
  { name: "Martin Odegaard", country: "Norway", position: "midfielder" },
  { name: "Andreas Schjelderup", country: "Norway", position: "midfielder" },
  { name: "Morten Thorsby", country: "Norway", position: "midfielder" },
  { name: "Kristian Thorstvedt", country: "Norway", position: "midfielder" },
  { name: "Oscar Bobb", country: "Norway", position: "forward" },
  { name: "Erling Haaland", country: "Norway", position: "forward" },
  { name: "Antonio Nusa", country: "Norway", position: "forward" },
  { name: "Alexander Sorloth", country: "Norway", position: "forward" },
  { name: "Jorgen Strand Larsen", country: "Norway", position: "forward" },
  // Panama
  { name: "Orlando Mosquera", country: "Panama", position: "goalkeeper" },
  { name: "Luis Mejia", country: "Panama", position: "goalkeeper" },
  { name: "Cesar Samudio", country: "Panama", position: "goalkeeper" },
  { name: "Cesar Blackman", country: "Panama", position: "defender" },
  { name: "Jorge Gutierrez", country: "Panama", position: "defender" },
  { name: "Amir Murillo", country: "Panama", position: "defender" },
  { name: "Fidel Escobar", country: "Panama", position: "defender" },
  { name: "Andres Andrade", country: "Panama", position: "defender" },
  { name: "Edgardo Farina", country: "Panama", position: "defender" },
  { name: "Jose Cordoba", country: "Panama", position: "defender" },
  { name: "Eric Davis", country: "Panama", position: "defender" },
  { name: "Jiovany Ramos", country: "Panama", position: "defender" },
  { name: "Roderick Miller", country: "Panama", position: "defender" },
  { name: "Anibal Godoy", country: "Panama", position: "midfielder" },
  { name: "Adalberto Carrasquilla", country: "Panama", position: "midfielder" },
  { name: "Carlos Harvey", country: "Panama", position: "midfielder" },
  { name: "Cristian Martinez", country: "Panama", position: "midfielder" },
  { name: "Jose Luis Rodriguez", country: "Panama", position: "midfielder" },
  { name: "Cesar Yanis", country: "Panama", position: "midfielder" },
  { name: "Yoel Barcenas", country: "Panama", position: "midfielder" },
  { name: "Alberto Quintero", country: "Panama", position: "midfielder" },
  { name: "Azarias Londono", country: "Panama", position: "midfielder" },
  { name: "Ismael Diaz", country: "Panama", position: "forward" },
  { name: "Cecilio Waterman", country: "Panama", position: "forward" },
  { name: "Jose Fajardo", country: "Panama", position: "forward" },
  { name: "Tomas Rodriguez", country: "Panama", position: "forward" },
  // Paraguay
  { name: "Roberto Fernández", country: "Paraguay", position: "goalkeeper" },
  { name: "Orlando Gill", country: "Paraguay", position: "goalkeeper" },
  { name: "Gastón Olveira", country: "Paraguay", position: "goalkeeper" },
  { name: "Gustavo Gómez", country: "Paraguay", position: "defender" },
  { name: "Júnior Alonso", country: "Paraguay", position: "defender" },
  { name: "Fabián Balbuena", country: "Paraguay", position: "defender" },
  { name: "Omar Alderete", country: "Paraguay", position: "defender" },
  { name: "Juan Caceres", country: "Paraguay", position: "defender" },
  { name: "Jose Canale", country: "Paraguay", position: "defender" },
  { name: "Alexandro Maidana", country: "Paraguay", position: "defender" },
  { name: "Gustavo Velázquez", country: "Paraguay", position: "defender" },
  { name: "Miguel Almirón", country: "Paraguay", position: "midfielder" },
  { name: "Kaku", country: "Paraguay", position: "midfielder" },
  { name: "Andrés Cubas", country: "Paraguay", position: "midfielder" },
  { name: "Ramón Sosa", country: "Paraguay", position: "midfielder" },
  { name: "Diego Gómez", country: "Paraguay", position: "midfielder" },
  { name: "Damián Bobadilla", country: "Paraguay", position: "midfielder" },
  { name: "Braian Ojeda", country: "Paraguay", position: "midfielder" },
  { name: "Matías Galarza", country: "Paraguay", position: "midfielder" },
  { name: "Maurício", country: "Paraguay", position: "midfielder" },
  { name: "Antonio Sanabria", country: "Paraguay", position: "forward" },
  { name: "Julio Enciso", country: "Paraguay", position: "forward" },
  { name: "Gabriel Ávalos", country: "Paraguay", position: "forward" },
  { name: "Alex Arce", country: "Paraguay", position: "forward" },
  { name: "Isidro Pitta", country: "Paraguay", position: "forward" },
  { name: "Gustavo Caballero", country: "Paraguay", position: "forward" },
  // Portugal
  { name: "Diogo Costa", country: "Portugal", position: "goalkeeper" },
  { name: "Jose Sa", country: "Portugal", position: "goalkeeper" },
  { name: "Rui Silva", country: "Portugal", position: "goalkeeper" },
  { name: "Ricardo Velho", country: "Portugal", position: "goalkeeper" },
  { name: "Ruben Dias", country: "Portugal", position: "defender" },
  { name: "Joao Cancelo", country: "Portugal", position: "defender" },
  { name: "Nelson Semedo", country: "Portugal", position: "defender" },
  { name: "Nuno Mendes", country: "Portugal", position: "defender" },
  { name: "Diogo Dalot", country: "Portugal", position: "defender" },
  { name: "Goncalo Inacio", country: "Portugal", position: "defender" },
  { name: "Renato Veiga", country: "Portugal", position: "defender" },
  { name: "Tomas Araujo", country: "Portugal", position: "defender" },
  { name: "Bernardo Silva", country: "Portugal", position: "midfielder" },
  { name: "Bruno Fernandes", country: "Portugal", position: "midfielder" },
  { name: "Ruben Neves", country: "Portugal", position: "midfielder" },
  { name: "Vitinha", country: "Portugal", position: "midfielder" },
  { name: "Joao Neves", country: "Portugal", position: "midfielder" },
  { name: "Matheus Nunes", country: "Portugal", position: "midfielder" },
  { name: "Samuel Costa", country: "Portugal", position: "midfielder" },
  { name: "Cristiano Ronaldo", country: "Portugal", position: "forward" },
  { name: "Joao Felix", country: "Portugal", position: "forward" },
  { name: "Rafael Leao", country: "Portugal", position: "forward" },
  { name: "Goncalo Guedes", country: "Portugal", position: "forward" },
  { name: "Goncalo Ramos", country: "Portugal", position: "forward" },
  { name: "Pedro Neto", country: "Portugal", position: "forward" },
  { name: "Francisco Conceicao", country: "Portugal", position: "forward" },
  { name: "Francisco Trincao", country: "Portugal", position: "forward" },
  // Qatar
  { name: "Salah Zakaria", country: "Qatar", position: "goalkeeper" },
  { name: "Meshaal Barsham", country: "Qatar", position: "goalkeeper" },
  { name: "Mahmoud Abunada", country: "Qatar", position: "goalkeeper" },
  { name: "Boualem Khoukhi", country: "Qatar", position: "defender" },
  { name: "Pedro Miguel", country: "Qatar", position: "defender" },
  { name: "Sultan Al Brake", country: "Qatar", position: "defender" },
  { name: "Al-Hashmi Al-Hussain", country: "Qatar", position: "defender" },
  { name: "Ayoub Al-Alawi", country: "Qatar", position: "defender" },
  { name: "Issa Laye", country: "Qatar", position: "defender" },
  { name: "Lucas Mendes", country: "Qatar", position: "defender" },
  { name: "Homam Al-Amin", country: "Qatar", position: "defender" },
  { name: "Ahmed Fathi", country: "Qatar", position: "midfielder" },
  { name: "Jassim Gaber", country: "Qatar", position: "midfielder" },
  { name: "Assim Madibo", country: "Qatar", position: "midfielder" },
  { name: "Abdulaziz Hatem", country: "Qatar", position: "midfielder" },
  { name: "Karim Boudiaf", country: "Qatar", position: "midfielder" },
  { name: "Mohammed Mannai", country: "Qatar", position: "midfielder" },
  { name: "Almoez Ali", country: "Qatar", position: "forward" },
  { name: "Akram Afif", country: "Qatar", position: "forward" },
  { name: "Tahsin Mohammed", country: "Qatar", position: "forward" },
  { name: "Edmílson Junior", country: "Qatar", position: "forward" },
  { name: "Ahmed Al-Ganehi", country: "Qatar", position: "forward" },
  { name: "Ahmed Alaa", country: "Qatar", position: "forward" },
  { name: "Hassan Al-Haydos", country: "Qatar", position: "forward" },
  { name: "Mohammed Muntari", country: "Qatar", position: "forward" },
  { name: "Yusuf Abdurisag", country: "Qatar", position: "forward" },
  // Saudi Arabia
  { name: "Mohammed Al Owais", country: "Saudi Arabia", position: "goalkeeper" },
  { name: "Nawaf Al Aqidi", country: "Saudi Arabia", position: "goalkeeper" },
  { name: "Ahmed Al Kassar", country: "Saudi Arabia", position: "goalkeeper" },
  { name: "Abdulelah Al Amri", country: "Saudi Arabia", position: "defender" },
  { name: "Hassan Tambakti", country: "Saudi Arabia", position: "defender" },
  { name: "Jehad Thikri", country: "Saudi Arabia", position: "defender" },
  { name: "Ali Lajami", country: "Saudi Arabia", position: "defender" },
  { name: "Hassan Kadesh", country: "Saudi Arabia", position: "defender" },
  { name: "Saud Abdulhamid", country: "Saudi Arabia", position: "defender" },
  { name: "Mohammed Abu Al Shamat", country: "Saudi Arabia", position: "defender" },
  { name: "Ali Majrashi", country: "Saudi Arabia", position: "defender" },
  { name: "Moteb Al Harbi", country: "Saudi Arabia", position: "defender" },
  { name: "Nawaf Boushal", country: "Saudi Arabia", position: "defender" },
  { name: "Sultan Al-Ghannam", country: "Saudi Arabia", position: "defender" },
  { name: "Mohammed Kanno", country: "Saudi Arabia", position: "midfielder" },
  { name: "Abdullah Al Khaibari", country: "Saudi Arabia", position: "midfielder" },
  { name: "Ziyad Al Johani", country: "Saudi Arabia", position: "midfielder" },
  { name: "Nasser Al Dawsari", country: "Saudi Arabia", position: "midfielder" },
  { name: "Musab Al Juwayr", country: "Saudi Arabia", position: "midfielder" },
  { name: "Alaa Al Hajji", country: "Saudi Arabia", position: "midfielder" },
  { name: "Salem Al Dawsari", country: "Saudi Arabia", position: "midfielder" },
  { name: "Khalid Al Ghannam", country: "Saudi Arabia", position: "midfielder" },
  { name: "Ayman Yahya", country: "Saudi Arabia", position: "midfielder" },
  { name: "Firas Al Buraikan", country: "Saudi Arabia", position: "forward" },
  { name: "Saleh Al Shehri", country: "Saudi Arabia", position: "forward" },
  { name: "Abdullah Al Hamdan", country: "Saudi Arabia", position: "forward" },
  // Scotland
  { name: "Craig Gordon", country: "Scotland", position: "goalkeeper" },
  { name: "Angus Gunn", country: "Scotland", position: "goalkeeper" },
  { name: "Liam Kelly", country: "Scotland", position: "goalkeeper" },
  { name: "Grant Hanley", country: "Scotland", position: "defender" },
  { name: "Jack Hendry", country: "Scotland", position: "defender" },
  { name: "Aaron Hickey", country: "Scotland", position: "defender" },
  { name: "Dom Hyam", country: "Scotland", position: "defender" },
  { name: "Scott McKenna", country: "Scotland", position: "defender" },
  { name: "Nathan Patterson", country: "Scotland", position: "defender" },
  { name: "Anthony Ralston", country: "Scotland", position: "defender" },
  { name: "Andy Robertson", country: "Scotland", position: "defender" },
  { name: "John Souttar", country: "Scotland", position: "defender" },
  { name: "Kieran Tierney", country: "Scotland", position: "defender" },
  { name: "Ryan Christie", country: "Scotland", position: "midfielder" },
  { name: "Finlay Curtis", country: "Scotland", position: "midfielder" },
  { name: "Lewis Ferguson", country: "Scotland", position: "midfielder" },
  { name: "Ben Gannon-Doak", country: "Scotland", position: "midfielder" },
  { name: "Billy Gilmour", country: "Scotland", position: "midfielder" },
  { name: "John McGinn", country: "Scotland", position: "midfielder" },
  { name: "Kenny McLean", country: "Scotland", position: "midfielder" },
  { name: "Scott McTominay", country: "Scotland", position: "midfielder" },
  { name: "Ché Adams", country: "Scotland", position: "forward" },
  { name: "Lyndon Dykes", country: "Scotland", position: "forward" },
  { name: "George Hirst", country: "Scotland", position: "forward" },
  { name: "Lawrence Shankland", country: "Scotland", position: "forward" },
  { name: "Ross Stewart", country: "Scotland", position: "forward" },
  // Senegal
  { name: "Édouard Mendy", country: "Senegal", position: "goalkeeper" },
  { name: "Mory Diaw", country: "Senegal", position: "goalkeeper" },
  { name: "Yehvann Diouf", country: "Senegal", position: "goalkeeper" },
  { name: "Krépin Diatta", country: "Senegal", position: "defender" },
  { name: "Antoine Mendy", country: "Senegal", position: "defender" },
  { name: "Kalidou Koulibaly", country: "Senegal", position: "defender" },
  { name: "El Hadji Malick Diouf", country: "Senegal", position: "defender" },
  { name: "Mamadou Sarr", country: "Senegal", position: "defender" },
  { name: "Moussa Niakhaté", country: "Senegal", position: "defender" },
  { name: "Abdoulaye Seck", country: "Senegal", position: "defender" },
  { name: "Ismail Jakobs", country: "Senegal", position: "defender" },
  { name: "Idrissa Gana Gueye", country: "Senegal", position: "midfielder" },
  { name: "Pape Gueye", country: "Senegal", position: "midfielder" },
  { name: "Lamine Camara", country: "Senegal", position: "midfielder" },
  { name: "Habib Diarra", country: "Senegal", position: "midfielder" },
  { name: "Pathé Ciss", country: "Senegal", position: "midfielder" },
  { name: "Pape Matar Sarr", country: "Senegal", position: "midfielder" },
  { name: "Bara Sapoko Ndiaye", country: "Senegal", position: "midfielder" },
  { name: "Sadio Mané", country: "Senegal", position: "forward" },
  { name: "Ismaïla Sarr", country: "Senegal", position: "forward" },
  { name: "Iliman Ndiaye", country: "Senegal", position: "forward" },
  { name: "Assane Diao", country: "Senegal", position: "forward" },
  { name: "Ibrahim Mbaye", country: "Senegal", position: "forward" },
  { name: "Nicolas Jackson", country: "Senegal", position: "forward" },
  { name: "Bamba Dieng", country: "Senegal", position: "forward" },
  { name: "Cherif Ndiaye", country: "Senegal", position: "forward" },
  // South Africa
  { name: "Ronwen Williams", country: "South Africa", position: "goalkeeper" },
  { name: "Ricardo Goss", country: "South Africa", position: "goalkeeper" },
  { name: "Sipho Chaine", country: "South Africa", position: "goalkeeper" },
  { name: "Khuliso Mudau", country: "South Africa", position: "defender" },
  { name: "Nkosinathi Sibisi", country: "South Africa", position: "defender" },
  { name: "Ime Okon", country: "South Africa", position: "defender" },
  { name: "Khulumani Ndamane", country: "South Africa", position: "defender" },
  { name: "Aubrey Modiba", country: "South Africa", position: "defender" },
  { name: "Samukelo Kabini", country: "South Africa", position: "defender" },
  { name: "Thabang Matuludi", country: "South Africa", position: "defender" },
  { name: "Olwethu Makhanya", country: "South Africa", position: "defender" },
  { name: "Kamgogelo Sebelebele", country: "South Africa", position: "defender" },
  { name: "Bradley Cross", country: "South Africa", position: "defender" },
  { name: "Mbekezeli Mbokazi", country: "South Africa", position: "defender" },
  { name: "Teboho Mokoena", country: "South Africa", position: "midfielder" },
  { name: "Thalente Mbatha", country: "South Africa", position: "midfielder" },
  { name: "Yaya Sithole", country: "South Africa", position: "midfielder" },
  { name: "Jayden Adams", country: "South Africa", position: "midfielder" },
  { name: "Oswin Appollis", country: "South Africa", position: "forward" },
  { name: "Iqraam Rayners", country: "South Africa", position: "forward" },
  { name: "Tshepang Moremi", country: "South Africa", position: "forward" },
  { name: "Relebohile Mofokeng", country: "South Africa", position: "forward" },
  { name: "Evidence Makgopa", country: "South Africa", position: "forward" },
  { name: "Themba Zwane", country: "South Africa", position: "forward" },
  { name: "Lyle Foster", country: "South Africa", position: "forward" },
  { name: "Thapelo Maseko", country: "South Africa", position: "forward" },
  // South Korea
  { name: "Jo Hyun-Woo", country: "South Korea", position: "goalkeeper" },
  { name: "Kim Seung-Gyu", country: "South Korea", position: "goalkeeper" },
  { name: "Song Bum-Keun", country: "South Korea", position: "goalkeeper" },
  { name: "Kim Min-Jae", country: "South Korea", position: "defender" },
  { name: "Jo Yu-Min", country: "South Korea", position: "defender" },
  { name: "Lee Han-Beom", country: "South Korea", position: "defender" },
  { name: "Kim Tae-Hyun", country: "South Korea", position: "defender" },
  { name: "Park Jin-Seop", country: "South Korea", position: "defender" },
  { name: "Lee Ki-Hyeok", country: "South Korea", position: "defender" },
  { name: "Lee Tae-Seok", country: "South Korea", position: "defender" },
  { name: "Seol Young-Woo", country: "South Korea", position: "defender" },
  { name: "Jens Castrop", country: "South Korea", position: "defender" },
  { name: "Kim Moon-Hwan", country: "South Korea", position: "defender" },
  { name: "Yang Hyun-Jun", country: "South Korea", position: "midfielder" },
  { name: "Paik Seung-Ho", country: "South Korea", position: "midfielder" },
  { name: "Hwang In-Beom", country: "South Korea", position: "midfielder" },
  { name: "Kim Jin-Kyu", country: "South Korea", position: "midfielder" },
  { name: "Bae Jun-Ho", country: "South Korea", position: "midfielder" },
  { name: "Um Ji-Sung", country: "South Korea", position: "midfielder" },
  { name: "Hwang Hee-Chan", country: "South Korea", position: "midfielder" },
  { name: "Lee Dong-Gyeong", country: "South Korea", position: "midfielder" },
  { name: "Lee Jae-Sung", country: "South Korea", position: "midfielder" },
  { name: "Lee Kang-In", country: "South Korea", position: "midfielder" },
  { name: "Oh Hyun-Kyu", country: "South Korea", position: "forward" },
  { name: "Son Heung-Min", country: "South Korea", position: "forward" },
  { name: "Cho Kyu-Sung", country: "South Korea", position: "forward" },
  // Spain
  { name: "Unai Simón", country: "Spain", position: "goalkeeper" },
  { name: "David Raya", country: "Spain", position: "goalkeeper" },
  { name: "Joan García", country: "Spain", position: "goalkeeper" },
  { name: "Marc Cucurella", country: "Spain", position: "defender" },
  { name: "Pau Cubarsí", country: "Spain", position: "defender" },
  { name: "Aymeric Laporte", country: "Spain", position: "defender" },
  { name: "Álex Grimaldo", country: "Spain", position: "defender" },
  { name: "Pedro Porro", country: "Spain", position: "defender" },
  { name: "Eric García", country: "Spain", position: "defender" },
  { name: "Marcos Llorente", country: "Spain", position: "defender" },
  { name: "Marc Pubill", country: "Spain", position: "defender" },
  { name: "Gavi", country: "Spain", position: "midfielder" },
  { name: "Rodri", country: "Spain", position: "midfielder" },
  { name: "Pedri", country: "Spain", position: "midfielder" },
  { name: "Martín Zubimendi", country: "Spain", position: "midfielder" },
  { name: "Fabián Ruiz", country: "Spain", position: "midfielder" },
  { name: "Álex Baena", country: "Spain", position: "midfielder" },
  { name: "Mikel Merino", country: "Spain", position: "midfielder" },
  { name: "Lamine Yamal", country: "Spain", position: "forward" },
  { name: "Nico Williams", country: "Spain", position: "forward" },
  { name: "Dani Olmo", country: "Spain", position: "forward" },
  { name: "Ferran Torres", country: "Spain", position: "forward" },
  { name: "Mikel Oyarzabal", country: "Spain", position: "forward" },
  { name: "Yéremy Pino", country: "Spain", position: "forward" },
  { name: "Borja Iglesias", country: "Spain", position: "forward" },
  { name: "Víctor Muñoz", country: "Spain", position: "forward" },
  // Sweden
  { name: "Viktor Johansson", country: "Sweden", position: "goalkeeper" },
  { name: "Kristoffer Nordfeldt", country: "Sweden", position: "goalkeeper" },
  { name: "Jacob Widell Zetterstrom", country: "Sweden", position: "goalkeeper" },
  { name: "Hjalmar Ekdal", country: "Sweden", position: "defender" },
  { name: "Gabriel Gudmundsson", country: "Sweden", position: "defender" },
  { name: "Isak Hien", country: "Sweden", position: "defender" },
  { name: "Emil Holm", country: "Sweden", position: "defender" },
  { name: "Gustaf Lagerbielke", country: "Sweden", position: "defender" },
  { name: "Victor Lindelöf", country: "Sweden", position: "defender" },
  { name: "Erik Smith", country: "Sweden", position: "defender" },
  { name: "Carl Starfelt", country: "Sweden", position: "defender" },
  { name: "Elliot Stroud", country: "Sweden", position: "defender" },
  { name: "Daniel Svensson", country: "Sweden", position: "defender" },
  { name: "Taha Ali", country: "Sweden", position: "midfielder" },
  { name: "Yasin Ayari", country: "Sweden", position: "midfielder" },
  { name: "Lucas Bergvall", country: "Sweden", position: "midfielder" },
  { name: "Jesper Karlström", country: "Sweden", position: "midfielder" },
  { name: "Ken Sema", country: "Sweden", position: "midfielder" },
  { name: "Mattias Svanberg", country: "Sweden", position: "midfielder" },
  { name: "Besfort Zeneli", country: "Sweden", position: "midfielder" },
  { name: "Alexander Bernhardsson", country: "Sweden", position: "forward" },
  { name: "Anthony Elanga", country: "Sweden", position: "forward" },
  { name: "Viktor Gyökeres", country: "Sweden", position: "forward" },
  { name: "Alexander Isak", country: "Sweden", position: "forward" },
  { name: "Gustaf Nilsson", country: "Sweden", position: "forward" },
  { name: "Benjamin Nygren", country: "Sweden", position: "forward" },
  // Switzerland
  { name: "Gregor Kobel", country: "Switzerland", position: "goalkeeper" },
  { name: "Yvon Mvogo", country: "Switzerland", position: "goalkeeper" },
  { name: "Marvin Keller", country: "Switzerland", position: "goalkeeper" },
  { name: "Manuel Akanji", country: "Switzerland", position: "defender" },
  { name: "Nico Elvedi", country: "Switzerland", position: "defender" },
  { name: "Ricardo Rodriguez", country: "Switzerland", position: "defender" },
  { name: "Silvan Widmer", country: "Switzerland", position: "defender" },
  { name: "Miro Muheim", country: "Switzerland", position: "defender" },
  { name: "Aurèle Amenda", country: "Switzerland", position: "defender" },
  { name: "Eray Cömert", country: "Switzerland", position: "defender" },
  { name: "Luca Jaquez", country: "Switzerland", position: "defender" },
  { name: "Granit Xhaka", country: "Switzerland", position: "midfielder" },
  { name: "Johan Manzambi", country: "Switzerland", position: "midfielder" },
  { name: "Remo Freuler", country: "Switzerland", position: "midfielder" },
  { name: "Denis Zakaria", country: "Switzerland", position: "midfielder" },
  { name: "Ardon Jashari", country: "Switzerland", position: "midfielder" },
  { name: "Djibril Sow", country: "Switzerland", position: "midfielder" },
  { name: "Christian Fassnacht", country: "Switzerland", position: "midfielder" },
  { name: "Michel Aebischer", country: "Switzerland", position: "midfielder" },
  { name: "Fabian Rieder", country: "Switzerland", position: "midfielder" },
  { name: "Rubén Vargas", country: "Switzerland", position: "midfielder" },
  { name: "Breel Embolo", country: "Switzerland", position: "forward" },
  { name: "Noah Okafor", country: "Switzerland", position: "forward" },
  { name: "Dan Ndoye", country: "Switzerland", position: "forward" },
  { name: "Zeki Amdouni", country: "Switzerland", position: "forward" },
  { name: "Cedric Itten", country: "Switzerland", position: "forward" },
  // Tunisia
  { name: "Aymen Dahmen", country: "Tunisia", position: "goalkeeper" },
  { name: "Sabri Ben Hessen", country: "Tunisia", position: "goalkeeper" },
  { name: "Abdelmouhib Chamakh", country: "Tunisia", position: "goalkeeper" },
  { name: "Montassar Talbi", country: "Tunisia", position: "defender" },
  { name: "Dylan Bronn", country: "Tunisia", position: "defender" },
  { name: "Omar Rekik", country: "Tunisia", position: "defender" },
  { name: "Yan Valery", country: "Tunisia", position: "defender" },
  { name: "Ali Abdi", country: "Tunisia", position: "defender" },
  { name: "Moutaz Neffati", country: "Tunisia", position: "defender" },
  { name: "Raed Chikhaoui", country: "Tunisia", position: "defender" },
  { name: "Adam Arous", country: "Tunisia", position: "defender" },
  { name: "Mohamed Amine Ben Hamida", country: "Tunisia", position: "defender" },
  { name: "Ellyes Skhiri", country: "Tunisia", position: "midfielder" },
  { name: "Hannibal Mejbri", country: "Tunisia", position: "midfielder" },
  { name: "Anis Ben Slimane", country: "Tunisia", position: "midfielder" },
  { name: "Hadj Mahmoud", country: "Tunisia", position: "midfielder" },
  { name: "Rani Khedira", country: "Tunisia", position: "midfielder" },
  { name: "Mortadha Ben Ouanes", country: "Tunisia", position: "midfielder" },
  { name: "Elias Achouri", country: "Tunisia", position: "forward" },
  { name: "Ismaël Gharbi", country: "Tunisia", position: "forward" },
  { name: "Elias Saad", country: "Tunisia", position: "forward" },
  { name: "Sebastian Tounekti", country: "Tunisia", position: "forward" },
  { name: "Firas Chaouat", country: "Tunisia", position: "forward" },
  { name: "Khalil Ayari", country: "Tunisia", position: "forward" },
  { name: "Hazem Mastouri", country: "Tunisia", position: "forward" },
  { name: "Rayan Elloumi", country: "Tunisia", position: "forward" },
  // Turkey
  { name: "Ugurcan Cakir", country: "Turkey", position: "goalkeeper" },
  { name: "Mert Gunok", country: "Turkey", position: "goalkeeper" },
  { name: "Altay Bayindir", country: "Turkey", position: "goalkeeper" },
  { name: "Merih Demiral", country: "Turkey", position: "defender" },
  { name: "Zeki Celik", country: "Turkey", position: "defender" },
  { name: "Caglar Soyuncu", country: "Turkey", position: "defender" },
  { name: "Mert Muldur", country: "Turkey", position: "defender" },
  { name: "Ferdi Kadioglu", country: "Turkey", position: "defender" },
  { name: "Ozan Kabak", country: "Turkey", position: "defender" },
  { name: "Abdulkerim Bardakci", country: "Turkey", position: "defender" },
  { name: "Eren Elmali", country: "Turkey", position: "defender" },
  { name: "Samet Akaydin", country: "Turkey", position: "defender" },
  { name: "Hakan Calhanoglou", country: "Turkey", position: "midfielder" },
  { name: "Kaan Ayhan", country: "Turkey", position: "midfielder" },
  { name: "Orkun Kokcu", country: "Turkey", position: "midfielder" },
  { name: "Ismail Yuksek", country: "Turkey", position: "midfielder" },
  { name: "Salih Ozcan", country: "Turkey", position: "midfielder" },
  { name: "Kerem Akturkoglu", country: "Turkey", position: "forward" },
  { name: "Irfan Can Kahveci", country: "Turkey", position: "forward" },
  { name: "Baris Apler Yilmaz", country: "Turkey", position: "forward" },
  { name: "Arda Guler", country: "Turkey", position: "forward" },
  { name: "Kenan Yildiz", country: "Turkey", position: "forward" },
  { name: "Yunus Akgun", country: "Turkey", position: "forward" },
  { name: "Oguz Aydin", country: "Turkey", position: "forward" },
  { name: "Deniz Gul", country: "Turkey", position: "forward" },
  { name: "Can Uzun", country: "Turkey", position: "forward" },
  // United States
  { name: "Chris Brady", country: "United States", position: "goalkeeper" },
  { name: "Matt Freese", country: "United States", position: "goalkeeper" },
  { name: "Matt Turner", country: "United States", position: "goalkeeper" },
  { name: "Max Arfsten", country: "United States", position: "defender" },
  { name: "Sergiño Dest", country: "United States", position: "defender" },
  { name: "Alex Freeman", country: "United States", position: "defender" },
  { name: "Mark McKenzie", country: "United States", position: "defender" },
  { name: "Tim Ream", country: "United States", position: "defender" },
  { name: "Chris Richards", country: "United States", position: "defender" },
  { name: "Antonee Robinson", country: "United States", position: "defender" },
  { name: "Miles Robinson", country: "United States", position: "defender" },
  { name: "Joe Scally", country: "United States", position: "defender" },
  { name: "Auston Trusty", country: "United States", position: "defender" },
  { name: "Tyler Adams", country: "United States", position: "midfielder" },
  { name: "Sebastian Berhalter", country: "United States", position: "midfielder" },
  { name: "Weston McKennie", country: "United States", position: "midfielder" },
  { name: "Cristian Roldan", country: "United States", position: "midfielder" },
  { name: "Brenden Aaronson", country: "United States", position: "midfielder" },
  { name: "Malik Tillman", country: "United States", position: "midfielder" },
  { name: "Tim Weah", country: "United States", position: "midfielder" },
  { name: "Alejandro Zendejas", country: "United States", position: "midfielder" },
  { name: "Christian Pulisic", country: "United States", position: "forward" },
  { name: "Gio Reyna", country: "United States", position: "forward" },
  { name: "Folarin Balogun", country: "United States", position: "forward" },
  { name: "Ricardo Pepi", country: "United States", position: "forward" },
  { name: "Haji Wright", country: "United States", position: "forward" },
  // Uruguay
  { name: "Fernando Muslera", country: "Uruguay", position: "goalkeeper" },
  { name: "Sergio Rochet", country: "Uruguay", position: "goalkeeper" },
  { name: "Santiago Mele", country: "Uruguay", position: "goalkeeper" },
  { name: "Ronald Araújo", country: "Uruguay", position: "defender" },
  { name: "José María Giménez", country: "Uruguay", position: "defender" },
  { name: "Santiago Bueno", country: "Uruguay", position: "defender" },
  { name: "Sebastián Cáceres", country: "Uruguay", position: "defender" },
  { name: "Mathías Olivera", country: "Uruguay", position: "defender" },
  { name: "Guillermo Varela", country: "Uruguay", position: "defender" },
  { name: "Matías Viña", country: "Uruguay", position: "defender" },
  { name: "Joaquín Piquerez", country: "Uruguay", position: "defender" },
  { name: "Juan Manuel Sanabria", country: "Uruguay", position: "defender" },
  { name: "Federico Valverde", country: "Uruguay", position: "midfielder" },
  { name: "Rodrigo Bentancur", country: "Uruguay", position: "midfielder" },
  { name: "Manuel Ugarte", country: "Uruguay", position: "midfielder" },
  { name: "Emiliano Martínez", country: "Uruguay", position: "midfielder" },
  { name: "Rodrigo Zalazar", country: "Uruguay", position: "midfielder" },
  { name: "Giorgian De Arrascaeta", country: "Uruguay", position: "midfielder" },
  { name: "Nicolás De La Cruz", country: "Uruguay", position: "midfielder" },
  { name: "Agustín Canobbio", country: "Uruguay", position: "midfielder" },
  { name: "Maximiliano Araújo", country: "Uruguay", position: "midfielder" },
  { name: "Brian Rodríguez", country: "Uruguay", position: "midfielder" },
  { name: "Facundo Pellistri", country: "Uruguay", position: "midfielder" },
  { name: "Darwin Núñez", country: "Uruguay", position: "forward" },
  { name: "Federico Viñas", country: "Uruguay", position: "forward" },
  { name: "Rodrigo Aguirre", country: "Uruguay", position: "forward" },
  // Uzbekistan
  { name: "Utkir Yusupov", country: "Uzbekistan", position: "goalkeeper" },
  { name: "Abduvohid Nematov", country: "Uzbekistan", position: "goalkeeper" },
  { name: "Botirali Ergashev", country: "Uzbekistan", position: "goalkeeper" },
  { name: "Abdukodir Khusanov", country: "Uzbekistan", position: "defender" },
  { name: "Khojiakbar Alijonov", country: "Uzbekistan", position: "defender" },
  { name: "Rustam Ashurmatov", country: "Uzbekistan", position: "defender" },
  { name: "Farrukh Sayfiev", country: "Uzbekistan", position: "defender" },
  { name: "Sherzod Nasrullaev", country: "Uzbekistan", position: "defender" },
  { name: "Umarbek Eshmurodov", country: "Uzbekistan", position: "defender" },
  { name: "Abdulla Abdullaev", country: "Uzbekistan", position: "defender" },
  { name: "Bekhruz Karimov", country: "Uzbekistan", position: "defender" },
  { name: "Jakhongir Urozov", country: "Uzbekistan", position: "defender" },
  { name: "Avazbek Ulmasaliev", country: "Uzbekistan", position: "defender" },
  { name: "Akmal Mozgovoy", country: "Uzbekistan", position: "midfielder" },
  { name: "Otabek Shukurov", country: "Uzbekistan", position: "midfielder" },
  { name: "Jamshid Iskanderov", country: "Uzbekistan", position: "midfielder" },
  { name: "Odiljon Hamrobekov", country: "Uzbekistan", position: "midfielder" },
  { name: "Jaloliddin Masharipov", country: "Uzbekistan", position: "midfielder" },
  { name: "Oston Urunov", country: "Uzbekistan", position: "midfielder" },
  { name: "Dostonbek Khamdamov", country: "Uzbekistan", position: "midfielder" },
  { name: "Azizjon Ganiev", country: "Uzbekistan", position: "midfielder" },
  { name: "Abbosbek Fayzullaev", country: "Uzbekistan", position: "midfielder" },
  { name: "Sherzod Esanov", country: "Uzbekistan", position: "midfielder" },
  { name: "Eldor Shomurodov", country: "Uzbekistan", position: "forward" },
  { name: "Igor Sergeev", country: "Uzbekistan", position: "forward" },
  { name: "Azizbek Amonov", country: "Uzbekistan", position: "forward" },
]
